language: node_js

cache: npm

git:
  depth: 1
  quiet: true

before_script:
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - npm run test
  - fossa init
  - fossa analyze

after-sucess:
  - ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
  - curl -s https://codecov.io/bash | bash

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
