language: node_js

cache: npm

git:
  depth: 1
  quiet: true

script:
  - npm run test

after-sucess:
  - ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
  - curl -s https://codecov.io/bash | bash

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
