language: node_js
node_js:
  - node

cache: npm

script:
  - ./bin/run --help
  - npm run test

after_success:
  - ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
  - curl -s https://codecov.io/bash | bash
